### ISSUE TITLE
Icons are not displayed in all menus/too large gaps after tried fix with user script

### ISSUE THREAD

**Issue by Speravir** [B00ze64/FF-Menu-Icon-Plus-CSS#12] opened 2023-07-02 22:29 UTC
_Note: I just report it here, but the credits go to user bananovic in German forum Camp Firefox, cf. thread [Größere Abstände zwischen den Menüsymbolen und dem Menütext](https://www.camp-firefox.de/forum/thema/136527/)._

In some main menus no icons are displayed. Apparently, you have asked for a solution at [CustomJSforFx](https://github.com/Aris-t2/CustomJSforFx) ([your request](https://github.com/Aris-t2/CustomJSforFx/issues/29#issuecomment-645107785)), and after some help by @Aris-t2 [you have created a script that works](https://github.com/Aris-t2/CustomJSforFx/issues/29#issuecomment-998433727) (at least, I found it only there). But this script produces a new issue: There are now too large gaps for most items between the icons and the labels, cf, images posted by bananovic: [image1](https://www.camp-firefox.de/attachment/42565-image1-jpg/), [image2](https://www.camp-firefox.de/attachment/42566-image2-jpg/), which provoked the request by bananovic. I confirm this observation.

Long story short, bananovic [found another, very simple solution](https://www.camp-firefox.de/forum/thema/136527/?postID=1228567#post1228567) consisting in altering a single value in your style code:
```css
menupopup[needsgutter] menu:not([icon], .menu-iconic), menupopup[needsgutter] menuitem:not([checked="true"], [icon], .menuitem-iconic) {
    --mip-menu-icon-margin: 0;/* changed value, was "-24px" before */
}
```
The value of zero is mine, bananovic used "-1px".

---
This said:

Why do you make it so difficult for yourself and other people who potentially may want to help you? I’ve searched for the particular rule and apparently you have used the almost same code 17 times. The rule set obviously differs between the styles only in the icons. Why don’t you just create a basic style (or one for the menus, one for the panel, one for the library) and then import this (these) into the styles for the icon sets? How exactly, is up to your choice, but for instance, you could take the one you actively use as the basic style. This could even be done with variables for every symbol which then are applied in the distinct rules for the various icon sets with the necessary value.

**Comment by B00ze64** [comment] 2023-07-05 02:23
Good day.

Ok, I tried with zero and it breaks the menus for me. Which OS are you using? Could it be Win11 and it's different than Win10? When I put zero some of the menus are 24px to the right.

As for having the code repeat, I tried just now to put it in a @import instead, but it broke the code, the menus were all wrong, maybe because I end-up importing the same code multiple times, I have no idea.

Regards,

**Comment by B00ze64** [comment] 2023-07-07 02:35
Alright I got all the menu-spacing stuff removed from all the css files, and used 2 new files that have to be imported from userChrome, instead. Thanks for the suggestion. I'm not releasing yet, as I found some missing icons I still have to fix.

**Comment by B00ze64** [comment] 2023-07-11 01:32
Well, if you are on Win11, then do you need to use 0 for mip-menu-icon-margin, or does it work OK at -24?

**Comment by B00ze64** [comment] 2023-07-29 00:32
Ok, I pushed a commit to mip_ConfigMenus.css where is uses 0 for Win11, can you grab it from here and test it?

**Comment by B00ze64** [comment] 2023-08-16 01:47
Nice find that bug, so I have no way of identifying Win 11. I don't know that Win 11 is the issue, but I cannot reproduce your bug on my Win 10 in any DPI (100%,125,150,175). Alright I'll revert the changes, thanks. Now I gotta fix the sidebar icons which Mozilla broke with v116.

**Comment by B00ze64** [comment] 2023-08-30 01:14
Wow, v117 broke pretty much every menu, this might take a while to fix, hopefully I can fix it, we'll see.

**Comment by B00ze64** [comment] 2023-09-15 01:19
Ok, Moz-Platform is deprecated, so I cannot have separate rules for Win11 and I can no longer support Win7. It is unknown if Win11 is really the problem as well, all I know is that I need that rule at -24 or the menus are all pushed to the right on my system. I incorporated the margin rule for Aris' restart menu item, thanks. I'm going to go ahead and close this bug.

**Closed by B00ze64** 2023-09-15 01:19 UTC
