### ISSUE TITLE
Scroll arrows pointlessly appearing

### ISSUE THREAD

**Issue by mzso** [B00ze64/FF-Menu-Icon-Plus-CSS#4] opened 2020-11-26 22:49 UTC
Hi!

I tried this (with silk theme), and immediately noticed this issue. Both tools and context menu shows the scroll arrows by default.
There would be no reason to scroll. The scrollbutton actully covers one menu item.

(FF 83 dev edition)

**Comment by B00ze64** [comment] 2020-11-27 02:16
You'll have to provide a screenshot as I do not have this issue with my FF83. This /could/ happen with the SVG icons (context menu only) since there is one icon I use which is bigger than 16x16, but not with Silk or other PNG icons...

**Comment by mzso** [comment] 2020-11-27 19:07
[**@B00ze64**](https://github.com/B00ze64) commented on [2020. nov. 27. 03:16 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/4#issuecomment-734536546 "2020-11-27T02:16:05Z - Replied by Github Reply Comments"):
> You'll have to provide a screenshot as I do not have this issue with my FF83. This /could/ happen with the SVG icons (context menu only) since there is one icon I use which is bigger than 16x16, but not with Silk or other PNG icons...

I tried, but didn't use SVG icons, because they were monochrome stuff.
It looks like this:


[2020-11-27_20-02-35.mp4.zip](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/files/5609295/2020-11-27_20-02-35.mp4.zip)

**Comment by B00ze64** [comment] 2020-11-28 03:46
Why d'you make a video? Just paste a screenshot into here on Github, I need to see what entries you have in those menus...

**Comment by mzso** [comment] 2020-11-28 06:53
> Why d'you make a video? Just paste a screenshot into here on Github, I need to see what entries you have in those menus...

Well, it shows that, and more. The arrow also appeared for a context menu that only had a single menu item.

**Comment by mzso** [comment] 2020-11-28 18:12
[**@B00ze64**](https://github.com/B00ze64) commented on [2020. nov. 28. 04:46 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/4#issuecomment-735035540 "2020-11-28T03:46:57Z - Replied by Github Reply Comments"):
> Why d'you make a video? Just paste a screenshot into here on Github, I need to see what entries you have in those menus...

It seems like all menus are affected, context or otherwise. Page action context menus are the most absurd where there is a single item covered by an (often flickering) scroll arrow.

**Comment by B00ze64** [comment] 2020-11-29 00:13
Well, I am unable to reproduce this, sorry, and flickering arrows are definitively not caused by this CSS. You must have other CSS that plays with the menus. Try removing all the "margin-top: 2px;" entries, see if that helps...

**Comment by B00ze64** [comment] 2020-11-29 00:30
Alright, I tried changing Windows' Text Zoom setting - I use 100% here but on high-DPI screens it uses 125% or 150% by default. That made little arrows appear at the bottom of the menus (not at the top). To fix this will require removing "**margin-top: 2px;**" from the CSS. Try it, just use search/replace to get rid of that line everywhere in the Silk CSS. Let me know if that fixes it for you.

**Comment by mzso** [comment] 2020-11-29 12:09
@B00ze64 
I see. I do have a custom DPI set (150%)
Thanks for the tip. It seems to have alleviated the problem. So far I haven't seen the scroll arrow in any menu that I could think to try.

**Comment by B00ze64** [comment] 2020-12-01 03:43
I had not thought of this when I first replied to you, then 30 minutes later I was reading something on Aris-t2's Github and someone mentioned DPI Scaling and there you go, I'd found the possible cause. Thanks for reporting the issue, I've pushed Release v1.4. Resolving this ticket.

**Closed by B00ze64** 2020-12-01 03:43 UTC

**Comment by mzso** [comment] 2021-04-11 08:08
Hi!
I recently reset windows. And I set DPI to 175% instead of 150%. And the scroll arrows re-appeared. So it seems the CSS doesn't work for everybody. I want back to 150%. So far so good.

**Comment by B00ze64** [comment] 2021-04-13 02:43
Hey. Well, the CSS is a work-around for Firefox not letting us change the CLASS of the menu items to menu-iconic using CSS. Firefox does its best to cope with the work-around but it's quite possible it does not work too well in some circumstances.

**Comment by mzso** [comment] 2021-04-13 23:29
[**@B00ze64**](https://github.com/B00ze64) commented on [2021. ápr. 13. 04:43 CEST](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/4#issuecomment-818390001 "2021-04-13T02:43:11Z - Replied by Github Reply Comments"):
> Hey. Well, the CSS is a work-around for Firefox not letting us change the CLASS of the menu items to menu-iconic using CSS. Firefox does its best to cope with the work-around but it's quite possible it does not work too well in some circumstances.

I thought it was maybe fixable, so I reported it.
